# -*- coding: utf-8 -*-
"""Hamming Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCCGW3fEbhAklCzYhffowa74ueAqeW8x
"""

import numpy as np

m = np.random.randint(2,size=(4,1))
print(m)

"""# Encoding"""

H = np.array([[1,1,1,0,1,0,0],
             [1,1,0,1,0,1,0],
             [1,0,1,1,0,0,1]])
G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,1,0],
             [1,1,0,1],
             [1,0,1,1]])
CA = (G @ m) % 2
print(CA)

"""# Sending"""

e = np.array([[1],[0],[0],[0],[0],[0],[0]])
CB = (CA + e) % 2
print(CB)

"""# Check and Correct"""

syndrome = (H @ CB) % 2
I_7 = np.identity(7, dtype=np.int8)
e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
for i in range(7):
  if(np.array_equiv((H @ CB) % 2, H[:, i])):
    e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
CA = (CB + e_i) % 2
print(CA)

"""# Decode"""

m = np.array([CA[0],CA[1],CA[2],CA[3]])
print(m)

"""# Classes"""

class HammingCode:

  def GeneratorMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,1,0],
             [1,1,0,1],
             [1,0,1,1]])
    return G

  def ParityCheckMatrix():
    H = np.array([[1,1,1,0,1,0,0],
             [1,1,0,1,0,1,0],
             [1,0,1,1,0,0,1]])
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    e = np.array([[1],[0],[0],[0],[0],[0],[0]])
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_7 = np.identity(7, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, H[:, i])):
        e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[0],CA[1],CA[2],CA[3]])
    return m