# -*- coding: utf-8 -*-
"""Repetition Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rj5CJ1D4q2_VZxsnGrtWTpeKag_dO9vE
"""

import numpy as np
import random

n = 4 # user input

"""# Encoding"""

G = np.ones([n,1], dtype=np.int8)
I = np.identity(n-1, dtype=np.int8)
ones = np.ones([n-1,1], dtype=np.int8)
H = np.concatenate((ones, I), axis=1)
d = np.random.randint(2,size=1) # data bit
codeword = G @ d

"""# Sending"""

error_i = random.randint(0,n-1)
codeword[error_i] = (codeword[error_i] + 1) % 2

"""# Checking"""

syndrome = (H @ codeword) % 2
print(syndrome)

"""# Decoding"""

majority = np.dot(codeword, G)
if(majority > n/2):
  result = 1
elif(majority < n/2):
  result = 0
else:
  result = "undecidable"
print(result)

"""# Class"""

class RepetitionCode:

  def GeneratorMatrix(n):
    G = np.ones([n,1], dtype=np.int8)
    return G

  def ParityCheckMatrix(n):
    I = np.identity(n-1, dtype=np.int8)
    ones = np.ones([n-1,1], dtype=np.int8)
    H = np.concatenate((ones, I), axis=1)
    return H

  def encode(databit, G, n):
    codeword = G @ databit
    return codeword

  def send(codeword, error):
    erronousword = (codeword + error) % 2
    return codeword

  def check(erronousword, H, n):
    syndrome = (H @ erronousword) % 2

  def decode(erronousword, G, n):
    majority = np.dot(codeword, G)
    if(majority >= n/2):
      result = 1
    else:
      result = 0
    return result